contract_management/api/urls.py
from django.urls import path
from . import views

app_name = 'contract_management'

urlpatterns = [
    path('performed/services', views.PerformedServicesView.as_view(),
         name='performed_services'),
    path('<str:card_number>/available/hospitals', views.AvailableHospitalsView.as_view(),
         name='available_hospitals'),
    path('contract/customer/create', views.ContractCustomerCreateView.as_view(),
         name='contract_customer_create'),
    path('contract_customer/<str:number>/detail', views.ContractCustomerDetailView.as_view(),
         name='contract_customer_detail'),
    path('customer/<str:search>/contract/list', views.CustomerContractListView.as_view(),
         name='customer_contract_list'),
    path('program/list', views.ProgramListView.as_view(),
         name='program_list'),
    


]

contract_management/urls.py
from django.urls import path
from . import views
app_name = 'contract_management'

urlpatterns = [
    path('contract/list/', views.ContractListView.as_view(), name='contract_list'),
    path('contract/create/', views.ContractCreateView.as_view(), name='contract_create'),
    path('contract/<int:pk>/update/', views.ContractUpdateView.as_view(), name='contract_update'),
    path('contract/<int:pk>/delete/', views.ContractDeleteView.as_view(), name='contract_delete'),

    path('contract/<int:contract>/program/list/', views.ContractProgramListView.as_view(),
         name='contract_program_list'),
    path('contract/<int:contract>/program/create/', views.ContractProgramCreateView.as_view(),
         name='contract_program_create'),
    path('contract/<int:contract>/program/<int:pk>/update/', views.ContractProgramUpdateView.as_view(),
         name='contract_program_update'),
    path('contract/<int:contract>/program/<int:pk>/delete/', views.ContractProgramDeleteView.as_view(),
         name='contract_program_delete'),

    path('contract/<int:contract>/program/<int:program>/package/list/',
         views.ContractProgramPackageListView.as_view(), name='contract_program_package_list'),
    path('contract/<int:contract>/program/<int:program>/package/create/',
         views.ContractProgramPackageCreateView.as_view(), name='contract_program_package_create'),
    path('contract/<int:contract>/program/<int:program>/package/<int:pk>/update/',
         views.ContractProgramPackageUpdateView.as_view(), name='contract_program_package_update'),
    path('contract/<int:contract>/program/<int:program>/package/<int:pk>/delete/',
         views.ContractProgramPackageDeleteView.as_view(), name='contract_program_package_delete'),

    path('contract/<int:pk>/result/', views.ContractResultView.as_view(),
         name='contract_result'),

    path('hospital/list/', views.HospitalListView.as_view(),
         name='hospital_list'),
    path('hospital/<int:pk>/update', views.HospitalUpdateView.as_view(),
         name='hospital_update'),

    path('insurance/list/', views.InsuranceListView.as_view(),
         name='insurance_list'),
    path('insurance/<int:pk>/update', views.InsuranceUpdateView.as_view(),
         name='insurance_update'),

    

    path('contract/contract_customer/list/', views.ContractCustomerListView.as_view(),
         name='contract_customer_list'),
    path('contract/contract_customer/<int:pk>/detail/', views.ContractCustomerDetailView.as_view(),
         name='contract_customer_detail'),
    path('contract/contract_customer/create/', views.ContractCustomerCreateView.as_view(),
         name='contract_customer_create'),
    path('contract/contract_customer/<int:pk>/delete/', views.ContractCustomerDeleteView.as_view(),
         name='contract_customer_delete'),
    

    path('contract/contract_hospital/list/', views.ContractHospitalListView.as_view(),
         name='contract_hospital_list'),
    path('contract/contract_hospital/confirm/list/', views.ContractHospitalConfirmListView.as_view(),
         name='contract_hospital_confir_list'),
    path('contract/contract_hospital/create/', views.ContractHospitalCreateView.as_view(),
         name='contract_hospital_create'),
    path('contract/contract_hospital/<int:pk>/update/', views.ContractHospitalUpdateView.as_view(),
         name='contract_hospital_update'),
    path('contract/contract_hospital/<int:pk>/delete/', views.ContractHospitalDeleteView.as_view(),
         name='contract_hospital_delete'),
    #promed
   
    #endpromed
    path('pro-med-contract/contract_hospital/list/', views.ProMedContractHospitalListView.as_view(),
         name='pro_med_contract_hospital_list'),
    path('pro-med-contract/contract_hospital/confirm/list/', views.ProMedContractHospitalConfirmListView.as_view(),
         name='pro_med_contract_hospital_confir_list'),
    path('pro-med-contract/contract_hospital/create/', views.ProMedContractHospitalCreateView.as_view(),
         name='pro_med_contract_hospital_create'),
    path('pro-med-contract/contract_hospital/<int:pk>/update/', views.ProMedContractHospitalUpdateView.as_view(),
         name='pro_med_contract_hospital_update'),
    path('pro-med-contract/contract_hospital/<int:pk>/delete/', views.ProMedContractHospitalDeleteView.as_view(),
         name='pro_med_contract_hospital_delete'),

    path('contract/<int:contract>/program/<int:program>/package/<int:package>/service/list/',
         views.ContractProgramPackageServiceListView.as_view(),
         name='contract_program_package_service_list'),
    path('contract/<int:contract>/program/<int:program>/package/<int:package>/service/result/list/',
         views.ContractProgramPackageResultListView.as_view(),
         name='contract_program_package_service_result_list'),
    path('package/<int:package>/service/<int:service>/delete', views.PackageServiceDeleteView.as_view(),
         name="package_service_delete"),

    path('hospital_package_status_update/<int:pk>',
         views.HospitalPackageStatusUpdate.as_view(),
         name='hospital_package_status_update'),
    path('hospital_package/service_export/<int:contract_hospital>', views.HospitalPackageServiceExportView.as_view(),
         name='hospital_package_service_export'),

    path('contract/<int:contract>/program_blank/create',
         views.ProgramBlankCreateView.as_view(), name='program_blank_create'),

    path('program_by_contract/<int:contract>', views.ProgramByContractView.as_view(),
         name='program_by_contract'),

    path('contract/<int:contract_hospital>/hospital/<int:hospital>/package/list/',
         views.ContractHospitalPackageListView.as_view(),
         name='contract_hospital_package_list'),
    #promed
     path('pro_med/contract/<int:contract_hospital>/hospital/<int:hospital>/package/list/',
         views.ProMedContractHospitalPackageListView.as_view(),
         name='pro_med_contract_hospital_package_list'),
    #endpromed
    path('contract/<int:contract_hospital>/hospital/<int:hospital>/package/<int:pk>/update/',
         views.ContractHospitalPackageUpdateView.as_view(),
         name='contract_hospital_package_update'),
    path('contract/<int:contract_hospital>/hospital/<int:hospital>/package/<int:pk>/delete/',
         views.ContractHospitalPackageDeleteView.as_view(), name='contract_hospital_package_delete'),

    path('contract/<int:contract_hospital>/hospital/<int:hospital>/package/<int:hospital_package>/service/list/',
         views.ContractHospitalPackageServiceListView.as_view(),
         name='contract_hospital_package_service_list'),
    #ProMed
     path('pro_med/contract/<int:contract_hospital>/hospital/<int:hospital>/package/<int:hospital_package>/service/list/',
         views.ProMedContractHospitalPackageServiceListView.as_view(),
         name='pro_med_contract_hospital_package_service_list'),
    #endpromed
    path('contract/<int:contract_hospital>/hospital/<int:hospital>/service/list/',
         views.ContractHospitalServiceListView.as_view(),
         name='contract_hospital_service_list'),
    path('pro-med-contract/<int:contract_hospital>/hospital/<int:hospital>/service/list/',
         views.ProMedContractHospitalServiceListView.as_view(),
         name='pro_med_contract_hospital_service_list'),


    path('contract/<int:contract_hospital>/hospital/<int:hospital>/service/excel/',
         views.ContractHospitalServiceExcelView.as_view(),
         name='contract_hospital_service_excel'),
    path('contract/<int:contract_hospital>/hospital/<int:hospital>/service/treaty_list/',
         views.ContractHospitalServiceTreatyListView.as_view(),
         name='contract_hospital_service_treaty_list'),
    path('pro-med-contract/<int:contract_hospital>/hospital/<int:hospital>/service/treaty_list/',
         views.ProMedContractHospitalServiceTreatyListView.as_view(),
         name='pro_med_contract_hospital_service_treaty_list'),

    
    path('hospital/<int:hospital>/package/<int:hospital_package>/service/form',
         views.HospitalPackageServiceFormView.as_view(), name="hospital_package_service_form"),

    path('contract_hospital/status_update',
         views.ContractHospitalStatusUpdateView.as_view(), name="contract_hospital_status_update"),

    path('pro-med-contract/list/', views.ProMedContractListView.as_view(), name='pro_med_contract_list'),
    path('pro-med-contract/create/', views.ProMedContractCreateView.as_view(), name='pro_med_contract_create'),
    path('pro-med-contract/<int:pk>/update/', views.ProMedContractUpdateView.as_view(), name='pro_med_contract_update'),
    path('pro-med-contract/<int:pk>/delete/', views.ProMedContractDeleteView.as_view(), name='pro_med_contract_delete'),

    path('pro-med-contract/<int:contract>/program/list/', views.ProMedContractProgramListView.as_view(),
         name='pro_med_contract_program_list'),
    path('pro-med-contract/<int:contract>/program/create/', views.ProMedContractProgramCreateView.as_view(),
         name='pro_med_contract_program_create'),
    path('pro-med-contract/<int:contract>/program/<int:pk>/update/', views.ProMedContractProgramUpdateView.as_view(),
         name='pro_med_contract_program_update'),
    path('pro-med-contract/<int:contract>/program/<int:pk>/delete/', views.ProMedContractProgramDeleteView.as_view(),
         name='pro_med_contract_program_delete'),

    path('pro-med-contract/<int:contract>/program_blank/create',
         views.ProMedProgramBlankCreateView.as_view(), name='pro_med_program_blank_create'),

    path('pro-med-contract/<int:contract>/program/<int:program>/package/list/',
         views.ProMedContractProgramPackageListView.as_view(), name='pro_med_contract_program_package_list'),
    path('pro-med-contract/<int:contract>/program/<int:program>/package/create/',
         views.ProMedContractProgramPackageCreateView.as_view(), name='pro_med_contract_program_package_create'),
    path('pro-med-contract/<int:contract>/program/<int:program>/package/<int:pk>/update/',

elmedi/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from rest_framework.authtoken import views

urlpatterns = i18n_patterns(
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('account/', include('account.urls', namespace='account')),
    path('program_management/', include('program_management.urls', namespace='program_management')),
    path('package_service_management/',
         include('package_service_management.urls', namespace='package_service_management')),
    path('package_icd_management/',
         include('package_icd_management.urls', namespace='package_icd_management')),
    path('contract_management/',
         include('contract_management.urls', namespace='contract_management')),
    path('hospital_service_management/',
         include('hospital_service_management.urls', namespace='hospital_service_management')),
    path('hospital_icd_management/',
         include('hospital_icd_management.urls', namespace='hospital_icd_management')),
    path('directory/', include('directory.urls', namespace='directory')),
    path('report_management/', include('report_management.urls', namespace='report_management')),
    path('import_data/', include('import_data.urls', namespace='import_data')),
    path('promedicine/', include('promedicine.urls', namespace='promedicine')),
)

urlpatterns += [
    path('admin/', admin.site.urls),    
    path('api/customer/', include('customer.api.urls', namespace='customer_api')),
    path('api/contract_management/', include('contract_management.api.urls', namespace='contract_management_api')),
    path('api/promedicine/', include('promedicine.api.urls', namespace='promedicine_api')),
    path('api/referral_management/', include('referral_management.api.urls', namespace='referral_management_api')),
    path('api/invoice_management/', include('invoice_management.api.urls', namespace='invoice_management_api')),
    path('api/document_management/', include('document_management.api.urls', namespace='document_management_api')),
    path('api-token-auth/', views.obtain_auth_token),
    path('rosetta/', include('rosetta.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

contract_management/api/views.py
import requests
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView, RetrieveAPIView
from rest_framework.response import Response
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from directory.models import Service
from directory.api.serializers import ServiceSerializer
from contract_management.models import Contract, Program
from contract_management.utils import get_performed_services
from promedicine.models import ProfessionalExamination, SpecialityService, ExaminationAppointment
from ..models import ContractCustomer
from .serializers import PerformedServiceSerializer, ContractCustomerSerializer, ProgramSerializer


class PerformedServicesView(APIView):

    def post(self, request):
        results = PerformedServiceSerializer(data=request.data)
        if results.is_valid(raise_exception=True):
            card_number = request.data.get('card_number')
            hospital = request.data.get('hospital')
            type_appeal = int(request.data.get('type_appeal', None))
            place = int(request.data.get('place', None))
            contract_customer = ContractCustomer.objects.get(number=card_number)
            program = contract_customer.program
            performed_services = get_performed_services(
                hospital, program, type_appeal, place)
            services = Service.objects.filter(id__in=performed_services)
            results = ServiceSerializer(services, many=True)
        return Response(results.data)


class AvailableHospitalsView(APIView):

    def get(self, request, *args, **kwargs):
        card_number = kwargs.get('card_number')
        contract_customer = ContractCustomer.objects.get(number=card_number)
        available_hospitals = contract_customer.get_available_hospitals()
        return Response(available_hospitals)


class ContractCustomerCreateView(CreateAPIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = ContractCustomerSerializer
    queryset = ContractCustomer.objects.all()


class ContractCustomerDetailView(RetrieveAPIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = ContractCustomerSerializer
    queryset = ContractCustomer.objects.all()
    lookup_field = 'number'


# Посмотреть список или создать направление
class CustomerContractListView(APIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        search = self.kwargs['search']
        contract_customer = ContractCustomer.objects.filter(customer__iin=search).all()
        serializer = ContractCustomerSerializer(contract_customer, many=True)
        return Response(serializer.data)


class ProgramListView(APIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        programs = Program.objects.all()
        serializer = ProgramSerializer(programs, many=True)
        return Response(serializer.data)

templates/contract_management/pro_med_contract_hospital/create.html
{% load i18n %}

<form action="{% url 'contract_management:pro_med_contract_hospital_create' %}" method="POST">
    {% csrf_token %}
    {% include "contract_management/pro_med_contract_hospital/form.html" %}
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">{% trans "Отмена" %}</button>
        <button type="submit" class="btn btn-primary btn-sm">{% trans "Сохранить" %}</button>
    </div>
</form>

templates/contract_management/pro_med_contract_hospital/delete.html
{% load i18n %}

<form action="{% url 'contract_management:pro_med_contract_hospital_delete' pk=object.id %}" method="POST">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle-1">{% trans "Удалить контракт" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12 text-center">
                <p style="color:#333;">{% trans "Номер контракта: " %}{{ object.contract_program.contract.number }}</p>
                <hr>
                <p style="color:#333;" class="mb-0 color-red"> {% trans "Вы уверены, что хотите удалить контракт с номером" %} "{{ object.contract_program.contract.number }}"?   </p>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="submit" class="btn btn-danger btn-sm" value='{% trans "Удалить" %}'>
         <a href="" class="btn btn-secondary btn-sm">{% trans "Отмена" %}</a>
    </div>
</form>

templates/contract_management/pro_med_contract_hospital/form.html
{% load widget_tweaks %}
{% load i18n %}

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLongTitle-1">{% trans "Добавить" %}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
<div class="modal-body">
    <div class="form-group">
        <b> {% trans "Контракт" %}</b>
        {{ form.contract|add_class:"form-control" }}
    </div>
    <div class="form-group">
        <b>{% trans "Клиника" %}</b>
        {{ form.hospital|add_class:"form-control" }}
    </div>
</div>

templates/contract_management/pro_med_contract_hospital/list.html
{% extends "base.html" %}
{% load contract_management_tags %}
{% load i18n %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="">{% trans "Статус размещения" %}</a>
    </li>
{% endblock %}
{% block content %}
<div class="contentbar" style="margin-top: 0;">
  <div class="card" style="padding: 10px;">
      <div class="row align-items-center">
          <div class="col-md-8">
              <input id="table-search" type="text" class="form-control" placeholder='{% trans "Поиск" %}'>
          </div>
          <div class="col-md-4 col-lg-4">
            <button class="w-100 btn btn-success open-universal-modal"
                data-url="{% url 'contract_management:pro_med_contract_hospital_create' %}">{% trans "Добавить клиник / провайдеров" %}</button>
          </div>
      </div>
      <div class="row mt-3">
          <div class="col-md-12">
              <div class="table-responsive m-b-30">
                  <table class="table" id="table-content">
                      <thead class="thead-light">
                        <tr>
                          <th style="width:300px;">{% trans "Клиника" %}</th>
                          <th class="text-center">{% trans "Страховой контракт" %}</th>
                          <th class="text-center">{% trans "Программа" %}</th>
                          <th class="text-center">{% trans "Дата начала" %}</th>
                          <th class="text-center">{% trans "Дата окончания" %}</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for contract_hospital in contract_hospitals %}
                          {% get_contract contract_hospital.contract as contract %}
                          {% get_contract_hospital contract contract_hospital.hospital as contract_hospitals_2  %}
                          {% get_hospital contract_hospital.hospital as hospital %}
                          <tr>
                            <td>{{ hospital.title }}</td>
                            <td  class="text-center">{{ contract.number }}</td>
                            <td  class="text-center">
                              {% for contract_hospital_2 in contract_hospitals_2 %}
                                <a href="{% url 'contract_management:pro_med_contract_hospital_service_list' hospital=contract_hospital_2.hospital.id contract_hospital=contract_hospital_2.id %}" class="a-link">
                                {{ contract_hospital_2.program.title }}
                              </a>
                                &nbsp&nbsp /
                                <a href="{% url 'contract_management:pro_med_contract_hospital_service_treaty_list' contract_hospital=contract_hospital_2.id hospital=contract_hospital_2.hospital.id %}" class="a-link">
                                  {% trans "Посмотреть спецификацию в договоре" %}
                                </a>
                              &nbsp&nbsp
                                <a href="#" class="open-universal-modal" data-url="{% url     'contract_management:pro_med_contract_hospital_delete' pk=contract_hospital_2.id %}">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                              </a>
                                <br>
                              {% endfor %}
                            </td>
                            <td class="text-center">{{ contract.start_date|date:"d.m.Y" }}</td>
                            <td class="text-center">{{ contract.end_date|date:"d.m.Y" }}</td>
                            <td class="text-center">
                              {% if contract_hospitals_2.first.status == 1 %}
                                  <button class="btn-sm btn  btn-primary change-status" data-contract="{{ contract.id }}" data-hospital="{{ hospital.id }}" data-status="2">{% trans "Отправить" %}</button>
                              {% elif contract_hospitals_2.first.status == 2 %}
                                  <button class="btn-sm btn  btn-success change-status" data-contract="{{ contract.id }}" data-hospital="{{ hospital.id }}" data-status="3" {% if request.user.user_type == 17 %} disabled {% endif %}>{% trans "Отправлен" %}</button>
                              {% elif contract_hospitals_2.first.status == 3 %}
                                  <button class="btn-sm btn  btn-info" data-contract="{{ contract.id }}" data-hospital="{{ hospital.id }}">{% trans "Заявка принята" %}</button>
                              {% else %}
                                    <button class="btn-sm btn  btn-success change-status" data-contract="{{ contract.id }}" data-hospital="{{ hospital.id }}" data-status="1">{% trans "Акцептовано, принять" %}</button>
                              {% endif %}
                            </td>
                          </tr>
                        {% empty %}
                          <tr align="center">
                            <td colspan="7">{% trans "Данные не найдены!" %}</td>
                          </tr>
                        {% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock %}

{% block modal %}
  <div class="modal fade bs-example-modal-lg" id="universal-modal" role="dialog" aria-labelledby="myLargeModalLabel" style="display: none;">
    <div class="modal-dialog" role="document">
      <div class="modal-content" id="universal-modal-content">

      </div>
    </div>
  </div>
{% endblock %}

{% block domready %}
      $(document).on("click",".open-universal-modal",function() {
          var url = $(this).data('url')
          $.ajax({
            url: url,
            success: function(data){
              $('#universal-modal-content').html(data)
              $('#universal-modal').modal('show')
            }
          })
      })

    $(document).on("change","#id_contract",function() {
      var contract = $(this).val()
      var url = "{% url 'contract_management:program_by_contract' contract=0 %}".replace('0', contract)
      $.ajax({
        url: url,
        success: function (data) {
          $("#id_program").html(data)
        }
      })
    })

    $(document).on("click",".change-status",function() {
      var contract = $(this).data('contract')
      var hospital = $(this).data('hospital')
      var status = $(this).data('status')
      $.ajax({
        url: "{% url 'contract_management:contract_hospital_status_update' %}",
        type: "POST",
        data: {
          contract: contract,
          hospital: hospital,
          status: status
        },
        success: function (data) {
          location.reload()
        }
      })
    })
{% endblock %}

templates/contract_management/pro_med_contract_hospital/update.html
{% load i18n %}

<form action="{% url 'contract_management:pro_med_contract_hospital_update' pk=object.id %}" method="POST">
    {% csrf_token %}
    {% include "contract_management/pro_med_contract_hospital/form.html" %}
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">{% trans "Отмена" %}</button>
        <button type="submit" class="btn btn-primary btn-sm">{% trans "Сохранить" %}</button>
    </div>
</form>