elmedi/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from rest_framework.authtoken import views

urlpatterns = i18n_patterns(
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('account/', include('account.urls', namespace='account')),
    path('program_management/', include('program_management.urls', namespace='program_management')),
    path('package_service_management/',
         include('package_service_management.urls', namespace='package_service_management')),
    path('package_icd_management/',
         include('package_icd_management.urls', namespace='package_icd_management')),
    path('contract_management/',
         include('contract_management.urls', namespace='contract_management')),
    path('hospital_service_management/',
         include('hospital_service_management.urls', namespace='hospital_service_management')),
    path('hospital_icd_management/',
         include('hospital_icd_management.urls', namespace='hospital_icd_management')),
    path('directory/', include('directory.urls', namespace='directory')),
    path('report_management/', include('report_management.urls', namespace='report_management')),
    path('import_data/', include('import_data.urls', namespace='import_data')),
    path('promedicine/', include('promedicine.urls', namespace='promedicine')),
)

urlpatterns += [
    path('admin/', admin.site.urls),    
    path('api/customer/', include('customer.api.urls', namespace='customer_api')),
    path('api/contract_management/', include('contract_management.api.urls', namespace='contract_management_api')),
    path('api/promedicine/', include('promedicine.api.urls', namespace='promedicine_api')),
    path('api/referral_management/', include('referral_management.api.urls', namespace='referral_management_api')),
    path('api/invoice_management/', include('invoice_management.api.urls', namespace='invoice_management_api')),
    path('api/document_management/', include('document_management.api.urls', namespace='document_management_api')),
    path('api-token-auth/', views.obtain_auth_token),
    path('rosetta/', include('rosetta.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

package_service_management/urls.py
from django.urls import path
from . import views
app_name = 'package_service_management'

urlpatterns = [
    path('package/list/', views.PackageListView.as_view(), name='package_list'),
    path('package/create/', views.PackageCreateView.as_view(), name='package_create'),
    path('package/<int:pk>/update/', views.PackageUpdateView.as_view(), name='package_update'),
    path('package/<int:pk>/delete/', views.PackageDeleteView.as_view(), name='package_delete'),

    path('pro_med/package/list/', views.ProMedPackageListView.as_view(), name='pro_med_package_list'),
    path('pro_med/package/create/', views.ProMedPackageCreateView.as_view(), name='pro_med_package_create'),
    path('pro_med/package/<int:pk>/update/', views.ProMedPackageUpdateView.as_view(), name='pro_med_package_update'),
    path('pro_med/package/<int:pk>/delete/', views.ProMedPackageDeleteView.as_view(), name='pro_med_package_delete'),


    path('package/evaluation/list/', views.PackageEvaluationListView.as_view(), name='package_evaluation_list'),
    path('pro_med/package/evaluation/list/', views.ProMedPackageEvaluationListView.as_view(), name='pro_med_package_evaluation_list'),
    path('package/<int:package>/service/list/', views.PackageServiceListView.as_view(),
         name='package_service_list'),

    path('pro_med/package/<int:package>/service/list/', views.ProMedPackageServiceListView.as_view(),
         name='pro_med_package_service_list'),

    path('package/<int:package>/service/evaluation/list/', views.PackageServiceEvaluationListView.as_view(),
         name='package_service_evaluation_list'),
    path('pro_med/package/<int:package>/service/evaluation/list/', views.ProMedPackageServiceEvaluationListView.as_view(),
         name='pro_med_package_service_evaluation_list'),
    path('package/<int:package>/service/form', views.PackageServiceFormView.as_view(),
         name="package_service_form"),
    path('package/<int:package>/service/setting/form',
         views.PackageServiceSettingFormView.as_view(),
         name="package_service_setting_form"),
    path('service/setting',
         views.ServiceSettingView.as_view(),
         name="service_setting"),
    path('service/setting/form',
         views.ServiceSettingFormView.as_view(),
         name="service_setting_form"),

    path('package/<int:package>/service/setting/', views.PackageServiceSettingView.as_view(),
         name='package_service_setting'),

    path('pro_med/package/<int:package>/service/setting/', views.ProMedPackageServiceSettingView.as_view(),
         name='pro_med_package_service_setting'),

    path('package/<int:package>/service/<int:service>/delete', views.PackageServiceDeleteView.as_view(),
         name="package_service_delete"),
]

program_management/urls.py
from django.urls import path
from . import views
app_name = 'program_management'

urlpatterns = [
    path('program/list/', views.ProgramListView.as_view(), name='program_list'),
    path('pro_med/program/list/', views.ProMedProgramListView.as_view(), name='pro_med_program_list'),
    path('program/create/', views.ProgramCreateView.as_view(), name='program_create'),
    path('pro_med/program/create/', views.ProMedProgramCreateView.as_view(), name='pro_med_program_create'),
    path('program/<int:pk>/update/', views.ProgramUpdateView.as_view(), name='program_update'),
    path('pro_med/program/<int:pk>/update/', views.ProMedProgramUpdateView.as_view(), name='pro_med_program_update'),
    path('program/<int:pk>/delete/', views.ProgramDeleteView.as_view(), name='program_delete'),
    path('pro_med/program/<int:pk>/delete/', views.ProMedProgramDeleteView.as_view(), name='pro_med_program_delete'),

    path('program/<int:program>/package/list/', views.ProgramPackageListView.as_view(),
         name='program_package_list'),
    path('pro_med/program/<int:program>/package/list/', views.ProMedProgramPackageListView.as_view(),
         name='pro_med_program_package_list'),
    path('program/<int:program>/package/create/', views.ProgramPackageCreateView.as_view(),
         name='program_package_create'),
    path('program/<int:program>/package/<int:pk>/update/', views.ProgramPackageUpdateView.as_view(),
         name='program_package_update'),
    path('pro_med/program/<int:program>/package/<int:pk>/update/', views.ProMedProgramPackageUpdateView.as_view(),
         name='pro_med_program_package_update'),
    path('program/<int:program>/package/<int:pk>/delete/', views.ProgramPackageDeleteView.as_view(),
         name='program_package_delete'),
    path('pro_med/program/<int:program>/package/<int:pk>/delete/', views.ProMedProgramPackageDeleteView.as_view(),
         name='pro_med_program_package_delete'),

    path('program/<int:program>/package_blank/create', views.PackageBlankCreateView.as_view(),
         name='package_blank_create'),
    path('pro_med/program/<int:program>/package_blank/create', views.ProMedPackageBlankCreateView.as_view(),
         name='pro_med_package_blank_create'),

    path('program/<int:program>/package/<int:package>/service/list/', views.PackageServiceListView.as_view(),
         name='package_service_list'),
    path('pro_med/program/<int:program>/package/<int:package>/service/list/', views.ProMedPackageServiceListView.as_view(),
         name='pro_med_package_service_list'),
    path('package/<int:package>/service/<int:service>/delete', views.PackageServiceDeleteView.as_view(),
         name="package_service_delete"),

    path('program/<int:program>/package/<int:package>/service/setting/',
         views.ProgramPackageServiceSettingView.as_view(),
         name='program_package_service_setting'),
    path('pro_med/program/<int:program>/package/<int:package>/service/setting/',
         views.ProMedProgramPackageServiceSettingView.as_view(),
         name='pro_med_program_package_service_setting'),

    path('program/<int:program>/package/<int:package>/service/setting/form',
         views.ProgramPackageServiceSettingFormView.as_view(),
         name="program_package_service_setting_form"),
]

program_management/models.py
from django.db import models
from program_management.abstract_models import ProgramMixin
from directory.models import Insurer
from package_service_management.abstract_models import PackageMixin, PackageServiceMixin
from django.utils.translation import gettext_lazy as _


# Программа
class Program(ProgramMixin):
    insurer = models.ForeignKey(Insurer, on_delete=models.CASCADE, null=True, blank=True)
    PROGRAM_TYPE_CHOICES = [
        (1, 'ДМС'),
        (2, 'ОМО'),
        (3, 'ОПМО')
    ]
    program_type = models.IntegerField(choices=PROGRAM_TYPE_CHOICES, default=1)


# Пакеты
class Package(PackageMixin):
    LIMIT_TYPE_PRIMARY = 1
    LIMIT_TYPE_PARENT = 2
    LIMIT_TYPE_SPOUSE = 3

    LIMIT_TYPE_CHOICES = [
        (LIMIT_TYPE_PRIMARY, _('Полное покрытие')),
        (LIMIT_TYPE_PARENT, _('Лимит на стоимость услуг')),
        (LIMIT_TYPE_SPOUSE, _('Лимит на количество услуг')),
    ]

    program = models.ForeignKey(Program, on_delete=models.CASCADE)
    limit = models.DecimalField(max_digits=10, decimal_places=1, null=True, blank=True)
    limit_type = models.IntegerField(choices=LIMIT_TYPE_CHOICES, default=1)


# Услуги пакета
class PackageService(PackageServiceMixin):
    package = models.ForeignKey(Package, on_delete=models.CASCADE)

program_management/forms.py
from django import forms
from package_service_management.models import Package as PackageBlank

from .models import Program, Package, PackageService


# Форма программы
class ProgramForm(forms.ModelForm):

    class Meta:
        model = Program
        fields = ['title', 'limit_percent', 'premium_percent']

class ProMedProgramForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProMedProgramForm, self).__init__(*args, **kwargs)
        self.fields['insurer'].required = True

        # Customize program_type choices to show only types 2 and 3
        self.fields['program_type'].choices = [
            choice for choice in self.fields['program_type'].choices if choice[0] in [2, 3]
        ]

    class Meta:
        model = Program
        fields = ['title', 'insurer', 'program_type']


class PackageForm(forms.ModelForm):
    class Meta:
        model = Package
        fields = ['title', 'description', 'program', 'limit', 'limit_type']
        widgets = {'program': forms.HiddenInput()}


class PackageServiceForm(forms.ModelForm):
    class Meta:
        model = PackageService
        fields = [
            'package', 'service', 'vhi_at_home_coefficient',
            'vhi_price', 'vhi_primary_health_care_coefficient',
            'vhi_clinical_diagnostic_coefficient', 'vhi_hospital_coefficient',
            'pay_base_price', 'pay_at_home_coefficient',
            'pay_primary_health_care_coefficient', 'pay_clinical_diagnostic_coefficient',
            'pay_hospital_coefficient', 'pay_base_price', 'is_checked', 'limit'
        ]


# Форма пакета
class PackageBlankForm(forms.ModelForm):
    package_blank = forms.ModelChoiceField(
        queryset=PackageBlank.objects.filter(insurer__isnull=True).all())

    def __init__(self, *args, **kwargs):
        self.program = kwargs.pop('program')
        super(PackageBlankForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Package
        fields = ['package_blank', 'limit', 'limit_type']
        exclude = ['title', 'description', 'program']

    def save(self, *args, **kwargs):
        form = super(PackageBlankForm, self).save(commit=False)
        package_blank = self.cleaned_data['package_blank']
        form.title = package_blank.title
        form.service = package_blank.service
        form.program = self.program
        form.description = package_blank.description
        form.save()
        package_services = package_blank.packageservice_set.all()
        for package_service in package_services:
            PackageService.objects.create(
                package=form,
                service=package_service.service,
                vhi_at_home_coefficient=package_service.vhi_at_home_coefficient,
                vhi_price=package_service.vhi_price,
                vhi_primary_health_care_coefficient=package_service.vhi_primary_health_care_coefficient,
                vhi_clinical_diagnostic_coefficient=package_service.vhi_clinical_diagnostic_coefficient,
                vhi_hospital_coefficient=package_service.vhi_hospital_coefficient,
                pay_base_price=package_service.pay_base_price,
                pay_at_home_coefficient=package_service.pay_at_home_coefficient,
                pay_primary_health_care_coefficient=package_service.pay_primary_health_care_coefficient,
                pay_clinical_diagnostic_coefficient=package_service.pay_clinical_diagnostic_coefficient,
                pay_hospital_coefficient=package_service.pay_hospital_coefficient,
                limit=package_service.limit

            )
        return form


class ProMedPackageBlankForm(PackageBlankForm):
    package_blank = forms.ModelChoiceField(queryset=PackageBlank.objects.none())

    def __init__(self, *args, **kwargs):
        insurer = kwargs.pop('insurer', None)
        super().__init__(*args, **kwargs)
        
        # If insurer is provided, filter the queryset
        if insurer:
            self.fields['package_blank'].queryset = PackageBlank.objects.filter(
                insurer__isnull=False, insurer=insurer)


    class Meta:
        model = Package
        fields = ['package_blank']


class PackageServiceSettingForm(forms.ModelForm):

    class Meta:
        model = PackageService
        fields = [
            'package', 'service', 'vhi_at_home_coefficient',
            'vhi_price', 'vhi_primary_health_care_coefficient',
            'vhi_clinical_diagnostic_coefficient', 'vhi_hospital_coefficient',
            'pay_base_price', 'pay_at_home_coefficient',
            'pay_primary_health_care_coefficient', 'pay_clinical_diagnostic_coefficient',
            'pay_hospital_coefficient', 'pay_base_price', 'is_checked', 'limit'
        ]

    def save(self, *args, **kwargs):
        form = super(PackageServiceSettingForm, self).save(commit=False)
        form.save()
        service_descendants = form.service.get_descendants()
        for service_descendant in service_descendants:
            package_service, created = PackageService.objects.get_or_create(
                service=service_descendant, package=form.package)
            package_service.vhi_at_home_coefficient = self.cleaned_data['vhi_at_home_coefficient']
            package_service.vhi_price = self.cleaned_data['vhi_price']
            package_service.vhi_primary_health_care_coefficient = self.cleaned_data['vhi_primary_health_care_coefficient']
            package_service.vhi_clinical_diagnostic_coefficient = self.cleaned_data['vhi_clinical_diagnostic_coefficient']
            package_service.vhi_hospital_coefficient = self.cleaned_data['vhi_hospital_coefficient']
            package_service.pay_base_price = self.cleaned_data['pay_base_price']
            package_service.pay_at_home_coefficient = self.cleaned_data['pay_at_home_coefficient']
            package_service.pay_primary_health_care_coefficient = self.cleaned_data['pay_primary_health_care_coefficient']
            package_service.pay_clinical_diagnostic_coefficient = self.cleaned_data['pay_clinical_diagnostic_coefficient']
            package_service.pay_hospital_coefficient = self.cleaned_data['pay_hospital_coefficient']
            package_service.pay_base_price = self.cleaned_data['pay_base_price']
            package_service.limit = self.cleaned_data['limit']
            package_service.is_checked = self.cleaned_data['is_checked']
            package_service.save()
        return form

templates/program_management/pro_med_program_package_service/list.html
{% extends "base.html" %}
{% load mptt_tags %}
{% load common_tags %}
{% load program_management_tags %}
{% load i18n %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'program_management:pro_med_program_list' %}">{% trans "Cписок професии" %}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'program_management:pro_med_program_package_list' program=program.id %}">{{ program.title }}</a>
    </li>
    <li class="breadcrumb-item active">
         <a href="">{{ package.title }}</a>
    </li>
{% endblock %}

{% block content %}
<style>
    input{
        width: 40px
    }
</style>
<div class="contentbar" style="margin-top: 0;">
    <div class="card" style="padding: 10px;">
        <a class="btn-right-ab btn btn-info btn-sm" href="{% url 'program_management:pro_med_program_package_service_setting' program=program.id package=package.id %}?base_service={{ package.service.id }}">
            {% trans "Выберите услуги в " %}{{ package|truncatechars:25 }} 
        </a>
        <div class="row">
            <!-- <div class="col-md-12">
                <div class="">
                    <input type="text" class="form-control" placeholder="Поиск услуг по коду и названию">
                </div>
            </div> -->
            <div class="col-md-12">
                <div class="scroll-table">
                    <table class="table table-bordered treetable mb-0">
                        <tr>
                            <th style="width:200px;">
                                <div>{% trans "Коды услу" %}</div>
                            </th>
                            <th>
                                <div>{% trans "Названия услуг" %}</div>                     
                            </th>
                            <th style="width:150px">{% trans "Редактирование" %}</th>
                        </tr>
                    </table>
                    <div class="scroll-table-body-none-header">
                        <table class="table table-bordered treetable mt-0" id="service-table">
                            <tbody>
                                {% for service in services %}
                                    {% is_leaf_node service.is_leaf_node as is_leaf_node %}
                                    <tr data-tt-id="{{ service.id }}" data-tt-parent-id='{{ service.parent.id }}'>
                                        <td style="width:200px;height: 30px;">
                                            {% if not is_leaf_node %}
                                            <span class='folder'>
                                                {{ service.code }}
                                            </span>
                                            {% else %}
                                            <span class='file'>
                                                {{ service.code }}
                                            </span>
                                            {% endif %}
                                        </td>
                                        <td>
                                            {{ service.title }}
                                        </td>
                                        <td class="text-center" style="width:150px">

                                            <input type="checkbox" name="is_checked" class="package-service-customize d-none" checked>
                                            <button data-service="{{ service.id }}"
                                                    class="fa fa-trash btn delete-package_service"></button>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- <div class="table-responsive m-b-30">
                    
                    <table id="service-table" class="table table-bordered">
                        <tr>
                            <th colspan="1" style="width: 200px;"><div>Коды услуг</div></th>
                            <th><div>Названия услуг</div></th>
                            <th style="width:150px;">Редактирование</th>
                        </tr>
                        
                        <tbody>
                            {% for service in services %}
                                {% is_leaf_node service.is_leaf_node as is_leaf_node %}
                                <tr data-tt-id="{{ service.id }}" data-tt-parent-id='{{ service.parent.id }}'>
                                    <td style="display: flex;align-items: center;height: 30px;">
                                        {% if not is_leaf_node %}
                                        <span class='folder'>
                                            {{ service.code }}
                                        </span>
                                        {% else %}
                                        <span class='file'>
                                            {{ service.code }}
                                        </span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {{ service.title }}
                                    </td>
                                    <td class="text-center">

                                        <input type="checkbox" name="is_checked" class="package-service-customize d-none" checked>
                                        <button data-service="{{ service.id }}"
                                                class="fa fa-trash btn delete-package_service"></button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block domready %}
$("#service-table").treetable({
expandable: true,
clickableNodeNames: true
})

function get_form_data(_this, closest_element, element){
    data = {}
    _this.closest(closest_element).find(element).each(function(){
        var name = $(this).attr('name')
        data[name] = $(this).val()
    })
    return data
}

$(document).on("blur", ".package-service-customize", function() {
    data = {}
    var service = $(this).closest('tr').data('tt-id')
    var data = get_form_data($(this), 'tr', '.package-service-customize')
    data['service'] = service
    data['package'] = "{{ package.id }}"
    var url = "{% url 'package_service_management:package_service_form' package=package.id %}"
    $.ajax({
        url: url,
        type: "POST",
        data: data,
        success: function(data){
            console.log(data)
        }
    })
})

$(document).on("click", ".delete-package_service", function() {
    var id = $(this).closest('tr').data('tt-id')
    var service = $(this).data('service')
    var package = "{{ package.id }}"
    var url = "{% url 'program_management:package_service_delete' package=package.id service=1234 %}".replace(/1234/, service)
    $.ajax({
        url: url,
        type: "POST",
        success: function(data){
            console.log(data)
            $("#service-table").treetable("removeNode", id)
        }
    })
})

{% endblock %}

templates/program_management/pro_med_program_package_service/setting.html
{% extends "base.html" %}
{% load mptt_tags %}
{% load common_tags %}
{% load program_management_tags %}
{% load i18n %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'program_management:pro_med_program_list' %}">{% trans "Cписок професии" %}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'program_management:pro_med_program_package_list' program=program.id %}">{{ program.title }}</a>
    </li>
    <li class="breadcrumb-item">
         <a href="{% url 'program_management:pro_med_package_service_list' program=program.id package=package.id %}">{{ package.title }}</a>

    </li>
    <li class="breadcrumb-item active">
         <a href="">{% trans "Добавить/создать услугу" %}</a>
    </li>
{% endblock %}

{% block content %}
<style>
	input{
		width: 50px
	}
</style>
<div class="contentbar" style="margin-top: 0;">
	<div class="card" style="padding: 10px;">
		<div>
			<a href="{% url 'program_management:package_service_list' program=program.id package=package.id %}" class="btn btn-success d-block btn-sm btn-right-ab">{% trans "Завершить выбор услуг" %}</a>
		</div>
		<div class="row align-items-center mt-3">
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="scroll-table">
					<table class="table table-bordered" style="margin-bottom: 0;padding-bottom: 0;">
			
							<tr>
								<th colspan="1" style="width: 200px;"><div>{% trans "Коды услуг" %}</div></th>
								<th><div>{% trans "Названия услуг" %}</div></th>
								<th style="width:156px;">{% trans "Редактирование" %}</th>
							</tr>
					</table>
					<div class="scroll-table-body">
						<table class="table table-bordered treetable mt-0" id="service-table">
							{% for service in services %}
								{% is_service_in_package package service as service_in_package  %}
								{% is_leaf_node service.is_leaf_node as is_leaf_node %}
								{% if package.service.id != service.id %}
									<tr data-tt-id="{{ service.id }}" data-tt-parent-id='{{ service.parent.id }}'>
										<td style="width: 200px;height: 30px;">
											{% if not is_leaf_node %}
											<span class='folder'>
												{{ service.code }}
											</span>
											{% else %}
											<span class='file'>
												{{ service.code }}
											</span>
											{% endif %}
										</td>
										<td>{{ service.title }}</td>
										<td class="text-center" style="width:150px">
											<input type="checkbox" class="program-package-service-check" name="is_checked"
		                                        {% is_checked service_in_package %}>
										</td>
									</tr>
								{% endif %}	
							{% empty %}
								<tr>
									<td colspan="3" align="center">
										<h6>Выберите услугу</h6>
									</td>
								</tr>

							{% endfor %}
						</table>
					</div>
				</div>
				
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block domready %}
$("#service-table").treetable({
	expandable: true,
	clickableNodeNames: true
})

function get_form_data(_this, closest_element, element){
	data = {}
	_this.closest(closest_element).find(element).each(function(){
		var name = $(this).attr('name')
		data[name] = $(this).val()
	})
	return data
}

$(document).on("blur", ".package-service-customize", function() {
	data = {}
	var service = $(this).closest('tr').data('tt-id')
	var data = get_form_data($(this), 'tr', '.package-service-customize')
	data['service'] = service
	data['package'] = "{{ package.id }}"
	var url = "{% url 'package_service_management:package_service_form' package=package.id %}"
	$.ajax({
		url: url,
		type: "POST",
		data: data,
		success: function(data){
			console.log(data)
		}
	})
})

$(document).on("change", ".program-package-service-check", function() {
	var service = $(this).closest('tr').data('tt-id')
	var element = "[name='" + $(this).attr('name') + "']"
	var is_checked = $(this).is(':checked')
	var data = get_form_data($(this), 'tr', '.package-service-customize')
	data['service'] = service
	data['program'] = "{{ program.id }}"
	data['package'] = "{{ package.id }}"
	data['is_checked'] = is_checked
	var url = "{% url 'program_management:program_package_service_setting_form' program=program.id package=package.id %}"
	$.ajax({
		url: url,
		type: "POST",
		data: data,
		success: function(data){
			if(is_checked){
				$("#service-table").treetable("checkNode", service, element)
			}
			else{
				$("#service-table").treetable("uncheckNode", service, element)
			}
		}
	})
})



$(document).on("change", "#id_base_service", function() {
	var base_service = $('#id_base_service').val()
	var searchParams = new URLSearchParams(window.location.search)
	if(base_service){
		searchParams.set("base_service", base_service)
	}
	window.location.search = searchParams.toString()
})

{% endblock %}